version: '3.8'
services:
    xtrabackup:
      image: perconalab/percona-xtrabackup:2.4
      profiles: 
        - xtrabackup
      volumes:
        - ./volumes/mysql/:/var/lib/mysql/
        
        - ./volumes/tmp/backup/:/backup/
      command: ["/usr/bin/xtrabackup -H192.168.33.222 -P3306 -u root -p**Admin** --backup --datadir=/var/lib/mysql/ --target-dir=/backup"]
      
    
    mysql:
      build:
        context: ./services/mysql
        dockerfile: Dockerfile
        args: 
          USER_ID: ${USER_ID:-1000}
          USER_GID: ${USER_GID:-1000}
      #container_name: bx-mysql
      user: ${USER_ID:-1000}:${USER_GID:-1000}
      hostname: mysql
      healthcheck:
        test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
      networks:
        - bitrix
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-**Admin**}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-sitemanager}
        MYSQL_USER: ${MYSQL_USER:-bitrix}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-**bitrix**}
        XTRABACKUP_PASSWORD: ${XTRABACKUP_PASSWORD:-xpassword}
        MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-1}
        CLUSTER_JOIN: ${CLUSTER_JOIN:-}
        CLUSTER_NAME: ${CLUSTER_NAME:-bitrix-cluster}
        TZ: ${TZ:-Europe/Moscow}
      command: '--innodb_strict_mode=OFF --character-set-server=utf8 --collation-server=utf8_unicode_ci 
                --skip-character-set-client-handshake --sql-mode=
                --transaction-isolation=READ-COMMITTED
                --pxc_strict_mode=PERMISSIVE' #for percona extradb cluster

    web:
      build:
        context: ./services/web
        dockerfile: dockerfile
        args: 
          USER_ID: ${USER_ID:-1000}
          USER_GID: ${USER_GID:-1000}
          PHP_VERSION: ${PHP_VERSION:-74}
      hostname: web
      #ports:
        #- 8088:80
        #- 8893-8895:8893-8895/tcp
        #- 443:443
      networks:
        - bitrix
#          ipv4_address: 172.16.16.4
      depends_on:
        - mysql
        - push
      volumes:
        - ${LOGS_PATH:-./services}/web/logs/crond:/var/log/crond
        - ${LOGS_PATH:-./services}/web/logs/xdebug:/var/log/xdebug
        - ${LOGS_PATH:-./services}/web/logs/httpd:/var/log/httpd
        - ${LOGS_PATH:-./services}/web/logs/php:/var/log/php
        - ${LOGS_PATH:-./services}/web/logs/supervisor:/var/log/supervisor
        - ./services/web/cron/bitrix:/etc/cron.d/bitrix
        - ./services/web/supervisor/supervisord.ini:/etc/supervisord.d/supervisord.ini
        - ./services/web/php.d/config/zx-bitrix.ini:/etc/php.d/zx-bitrix.ini
        - ./services/web/httpd/config/conf/httpd.conf:/etc/httpd/conf/httpd.conf
        - ./services/web/httpd/config/conf.d/default.conf:/etc/httpd/conf.d/default.conf
        - ./services/web/httpd/config/conf.modules.d/00-mpm.conf:/etc/httpd/conf.modules.d/00-mpm.conf
        - ./services/web/cron:/etc/cron.d
      #command: ["/root/entry-web.sh"]
      environment:
        USER_ID: ${USER_ID:-1000}
        USER_GID: ${USER_GID:-1000}
      entrypoint: [ "/entrypoint.sh" ]
      #command: ["/usr/bin/supervisord"]
    
    nginx:
      build:
        context: ./services/web/nginx
        args: 
          USER_ID: ${USER_ID:-1000}
          USER_GID: ${USER_GID:-1000}
          BITRIX_PORT: ${BITRIX_PORT:-80}
          BITRIX_SSL_PORT: ${BITRIX_SSL_PORT:-443}
      ports:
        - ${BITRIX_PORT:-80}:80
        - ${BITRIX_SSL_PORT:-443}:443
        #открываем, если нужен доступ снаружи для push
        #- 8893-8895:8893-8895
      networks:
        - bitrix
  #          ipv4_address: 172.16.16.4
      depends_on:
        - web
      environment:
        USER_ID: ${USER_ID:-1000}
        USER_GID: ${USER_GID:-1000}
        BITRIX_PORT: ${BITRIX_PORT:-80}
        BITRIX_SSL_PORT: ${BITRIX_SSL_PORT:-443}
      volumes:
        - ./services/web/logs/nginx:/var/log/nginx
        - ./services/web/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        - ./services/web/nginx/config/sites-available:/etc/nginx/sites-available
        - ./services/web/nginx/config/conf.d:/etc/nginx/.conf.d
      #entrypoint: [ "/docker-entrypoint.d/entry.sh" ]
      

    redis:
      build: 
        context: ./services/redis
        dockerfile: dockerfile
      networks:
        - bitrix
      volumes:
        - redis-sock:/tmp/
        #- ./services/tmp/:/tmp/
        - ./services/redis/config/redis.conf:/usr/local/etc/redis/redis.conf 
    
    push:
      build:
        context: ./services/push
        dockerfile: dockerfile
        args: 
          USER_ID: $USER_ID
          TZ: $TZ:-Europe/Moscow
      hostname: push
      environment:
        USER_ID: ${USER_ID:-1000}
      volumes:
        - redis-sock:/tmp/
        #- ./services/tmp/:/tmp/
        - ${LOGS_PATH:-./services}/push/logs/:/var/log/
        - ./services/push/supervisor/supervisord.ini:/etc/supervisord.d/supervisord.ini
      #ports:
        #- 8010-8015:8010-8015/tcp
        #- 9010-9011:9010-9011/tcp
      networks:
        - bitrix
#          ipv4_address: 172.16.16.4
      depends_on:
        - redis
      entrypoint:  [ "/entrypoint.sh" ]
    
    haproxy:
      image: haproxy:alpine
      profiles: 
        - haproxy
      #ports:
        #- $BITRIX_PORT:8088
        #- $BITRIX_SSL_PORT:443
      depends_on:
        - nginx
      restart:
        unless-stopped 
      volumes:
        - ${LOGS_PATH:-./services}/haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
        - ./services/haproxy/ssl:/ssl
      networks:
        - bitrix
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - 33333:80
      networks:
        - bitrix
      environment:
 #      PMA_ARBITRARY: 1
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
#       PMA_ABSOLUTE_URI: /phpmyadmin

    

volumes: 
  redis-sock:      
    

networks:
  bitrix:
#    name: bitrix_net
#    ipam:
#      config:
#        - subnet: 172.16.16.0/24

    