version: '3.8'
services:
  ftp:
    build:
      context: ./services/ftp
      dockerfile: dockerfile
    environment:
      USERS: "bitrix|123456|/ftp|${USER_ID}"
    volumes:
      - www:/ftp
    ports:
      - "$FTP_PORT:21"
      #- "21000-21010:21000-21010"
  
  mysql:
    volumes:
      - mysql:/var/lib/mysql

  web:
    volumes:
      - www:/var/www/html/bx-site/
      #- ./bitrixsetup.php:/var/www/html/bx-site/bitrixsetup.php
      #- ./restore.php:/var/www/html/bx-site/restore.php
   
  nginx:
    volumes:
      - www:/var/www/html/bx-site/

volumes:
  mysql:
  www: