FROM alpine:3.13

COPY entrypoint.sh /entrypoint.sh
COPY vsftpd.conf /etc/vsftpd/vsftpd.conf

RUN apk --no-cache add vsftpd && \
    chmod +x /entrypoint.sh

EXPOSE 21 21000-21010
VOLUME /ftp

STOPSIGNAL SIGKILL

ENTRYPOINT ["/entrypoint.sh"]