ARG PHP_VER
FROM php:${PHP_VER:-8.0}-apache-buster
ARG USER_ID
ENV USER_ID=$USER_ID
ARG USER_GID
ENV USER_GID=$USER_GID
ARG TZ=Europe/Moscow
ENV TZ=$TZ
     COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
     RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install bash git autoconf cron fonts-freefont-ttf  libpq-dev libfreetype6-dev libfreetype6 graphviz build-essential zip unzip default-mysql-client
     RUN install-php-extensions bcmath exif ffi gettext gmp igbinary imap intl ldap mbstring \
         mysqli opcache pdo pdo_mysql pcntl pgsql pdo_pgsql pcov soap sqlite3 swoole redis readline xml zip memcache sockets xdebug gd zlib
     RUN a2enmod * -q || true && \
          a2dismod dav_fs dav dav_lock -q || true

     RUN  ln -f -s /usr/share/zoneinfo/$TZ /etc/localtime && \
          groupmod --gid $USER_GID www-data  && \
          usermod --uid $USER_ID www-data && \
          mkdir -p /var/www/html/bx-site && \
          chown www-data:www-data /var/www/html/bx-site && \
          mkdir -p /home/bitrix/.bx_temp/sitemanager && \
          chmod -R 777 /home/bitrix/.bx_temp/sitemanager && \
          mkdir -p /tmp/session && \
          chown www-data:www-data /tmp/session && \
          mkdir -p /var/lib/php/session && \
          chown www-data:www-data /var/lib/php/session && \
          mkdir -p /tmp/php_upload && \
          chmod -R 777 /tmp/php_upload && \
          chown www-data:www-data /var/www/html/bx-site 
     COPY ./cron/bitrix /etc/cron.d/bitrix

     