FROM centos:7
     RUN yum update -y && \
          rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
          rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
          yum-config-manager --enable remi-php74 && \
          yum install -y epel-release && \
          yum update -y && \
          yum -y install yum-utils \
          httpd \
          supervisor \
          php php-cli php-common \
          php-devel php-fedora-autoloader php-gd \
          php-imap php-json php-ldap php-mbstring \
          php-mysqlnd php-opcache php-pdo \
          php-pear php-pear-DB php-pecl-apcu \
          php-pecl-apcu-bc php-pecl-geoip \
          php-pecl-mcrypt php-pecl-memcache  \
          php-pecl-ssh2 php-process php-pspell php-xml php-zipstream \
          php-zip \
          nginx crontabs mc \
          php-pecl-redis gd-devel httpd-mod_session net-tools && \
          yum clean all && \
          ln -f -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
     #RUN groupadd apache && useradd -M nginx -g apache
     COPY ./httpd/config/ /etc/httpd
     COPY ./php.d/config/ /etc/php.d
     COPY ./cron/ /etc/cron.d
     COPY ./entrypoint.sh /
     COPY ./supervisor/ /etc/supervisord.d
     RUN mkdir -p /var/www/html/bx-site && chown -R nginx:apache /var/www/html/bx-site
     
     RUN chmod +x /entrypoint.sh
   
     #EXPOSE 80
     #EXPOSE 443
     EXPOSE 8090

     