FROM nginx:1.21-alpine
    
    ARG ARG_APP_TIMEZONE=Europe/Moscow
    ENV APP_TIMEZONE=${ARG_APP_TIMEZONE}
    ARG USER_ID
    ENV USER_ID=$USER_ID
    ARG BITRIX_PORT
    ENV BITRIX_PORT=$BITRIX_PORT
    COPY entrypoint.sh /docker-entrypoint.d/entry.sh
    # https://wiki.alpinelinux.org/wiki/Setting_the_timezone
    RUN echo "${APP_TIMEZONE}" && apk --update add tzdata mc shadow && \
    cp /usr/share/zoneinfo/${APP_TIMEZONE} /etc/localtime && \
    echo $APP_TIMEZONE > /etc/timezone && \
    apk del tzdata && \ 
    mkdir -p /var/log/nginx && \
    mkdir -p /home/bitrix/.bx_temp/sitemanager  && \
    chmod -R 777 /home/bitrix/.bx_temp/sitemanager && \
    usermod --uid $USER_ID nginx && \
    chmod +x /docker-entrypoint.d/entry.sh

    #RUN addgroup -S bitrix -g 600 && adduser bitrix -D -u 600 -G bitrix root
    COPY ./config/ /etc/nginx
    
    #RUN mkdir -p /var/www/html/bx-site && chown -R nginx:apache /var/www/html/bx-site

    #user nginx
   
    EXPOSE 80
    EXPOSE 443
    EXPOSE 8893-8895
    EXPOSE $BITRIX_PORT
    #ENTRYPOINT [ "/entrypoint.sh" ]

     